Update yml

diff --git a/.github/workflows/native-compile-platforms.yml b/.github/workflows/native-compile-platforms.yml
--- a/.github/workflows/native-compile-platforms.yml
+++ b/.github/workflows/native-compile-platforms.yml
@@ -194,75 +194,75 @@ jobs:
   #         ./gradlew :CocosGame:assembleDebug --quiet
   #         echo "Compile Android Debug Done!"
 
-  # compile_mac_x86_64:
-  #   name: "MacOS x86_64"
-  #   if: 
-  #     (! contains(github.event.pull_request.body, '[X] does not change any runtime related code or build configuration'))
-  #   runs-on: macos-latest
-  #   steps:
-  #     - uses: actions/checkout@v2
-  #     # - uses: actions/setup-python@v2
-  #     #   with:
-  #     #     python-version: "3.x"
+  compile_mac_x86_64:
+    name: "MacOS x86_64"
+    if: 
+      (! contains(github.event.pull_request.body, '[X] does not change any runtime related code or build configuration'))
+    runs-on: macos-latest
+    steps:
+      - uses: actions/checkout@v2
+      # - uses: actions/setup-python@v2
+      #   with:
+      #     python-version: "3.x"
 
-  #         # EXT_VERSION=`node ./.github/workflows/get-native-external-version.js`
-  #         # git clone --branch $EXT_VERSION --depth 1 https://github.com/cocos/cocos-engine-external native/external
+          # EXT_VERSION=`node ./.github/workflows/get-native-external-version.js`
+          # git clone --branch $EXT_VERSION --depth 1 https://github.com/cocos/cocos-engine-external native/external
 
-  #     - name: Download external libraries
-  #       shell: bash
-  #       run: |
-  #         git clone --branch test-swig --depth 1 https://github.com/dumganhar/cocos-engine-external native/external
+      - name: Download external libraries
+        shell: bash
+        run: |
+          git clone --branch test-swig --depth 1 https://github.com/dumganhar/cocos-engine-external native/external
 
-  #     - name: Generate bindings
-  #       run: |
-  #         cd ./native/tools/swig-config
-  #         ./genbindings.sh
-  #     # - uses: nttld/setup-ndk@v1
-  #     #   id: setup-ndk
-  #     #   with:
-  #     #     ndk-version: r21e
-  #     #     add-to-path: false
-  #     # - name: Generate bindings
-  #     #   env:
-  #     #     ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
-  #     #   run: |
-  #     #     python -m pip install PyYAML==5.4.1 Cheetah3
-  #     #     python ./native/tools/tojs/genbindings.py
-  #     #     rm ./native/tools/tojs/userconf.ini
-  #     # - name: Compile
-  #     #   env:
-  #     #     COCOS_ENGINE_DEV: 1
-  #     #   run: |
-  #     #     NUM_OF_CORES=`getconf _NPROCESSORS_ONLN`
-  #     #     NATIVE_ROOT=$GITHUB_WORKSPACE/native
-  #     #     echo "Compiling MacOSX ... "
-  #     #     cd  $GITHUB_WORKSPACE/templates/mac
-  #     #     echo "message(STATUS \"hook before \${CC_TARGET_NAME}\")" >> Pre-Sample.cmake
-  #     #     echo "message(STATUS \"hook after \${CC_TARGET_NAME}\")" >> Post-Sample.cmake
-  #     #     mkdir -p build-mac/proj
-  #     #     touch build-mac/proj/cfg.cmake
-  #     #     echo "set(CC_USE_VULKAN OFF)" >> build-mac/proj/cfg.cmake
-  #     #     echo "set(CC_USE_GLES2 OFF)" >> build-mac/proj/cfg.cmake
-  #     #     echo "set(CC_USE_GLES3 OFF)" >> build-mac/proj/cfg.cmake
-  #     #     echo "set(CC_USE_METAL ON)" >> build-mac/proj/cfg.cmake
-  #     #     echo "set(USE_WEBSOCKET_SERVER OFF)" >> build-mac/proj/cfg.cmake
-  #     #     echo "set(CMAKE_CXX_STANDARD_REQUIRED ON)" >> build-mac/proj/cfg.cmake
-  #     #     mkdir build-mac/assets
+      - name: Generate bindings
+        run: |
+          cd ./native/tools/swig-config
+          ./genbindings.sh
+      # - uses: nttld/setup-ndk@v1
+      #   id: setup-ndk
+      #   with:
+      #     ndk-version: r21e
+      #     add-to-path: false
+      # - name: Generate bindings
+      #   env:
+      #     ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
+      #   run: |
+      #     python -m pip install PyYAML==5.4.1 Cheetah3
+      #     python ./native/tools/tojs/genbindings.py
+      #     rm ./native/tools/tojs/userconf.ini
+      # - name: Compile
+      #   env:
+      #     COCOS_ENGINE_DEV: 1
+      #   run: |
+      #     NUM_OF_CORES=`getconf _NPROCESSORS_ONLN`
+      #     NATIVE_ROOT=$GITHUB_WORKSPACE/native
+      #     echo "Compiling MacOSX ... "
+      #     cd  $GITHUB_WORKSPACE/templates/mac
+      #     echo "message(STATUS \"hook before \${CC_TARGET_NAME}\")" >> Pre-Sample.cmake
+      #     echo "message(STATUS \"hook after \${CC_TARGET_NAME}\")" >> Post-Sample.cmake
+      #     mkdir -p build-mac/proj
+      #     touch build-mac/proj/cfg.cmake
+      #     echo "set(CC_USE_VULKAN OFF)" >> build-mac/proj/cfg.cmake
+      #     echo "set(CC_USE_GLES2 OFF)" >> build-mac/proj/cfg.cmake
+      #     echo "set(CC_USE_GLES3 OFF)" >> build-mac/proj/cfg.cmake
+      #     echo "set(CC_USE_METAL ON)" >> build-mac/proj/cfg.cmake
+      #     echo "set(USE_WEBSOCKET_SERVER OFF)" >> build-mac/proj/cfg.cmake
+      #     echo "set(CMAKE_CXX_STANDARD_REQUIRED ON)" >> build-mac/proj/cfg.cmake
+      #     mkdir build-mac/assets
 
-  #     #     RES_DIR=$GITHUB_WORKSPACE/templates/mac/build-mac
-  #     #     cd build-mac
-  #     #     cmake ../ -GXcode -DCMAKE_OSX_ARCHITECTURES=x86_64 -DRES_DIR=$RES_DIR -DCOCOS_X_PATH=$NATIVE_ROOT
-  #     #     set +e
-  #     #     cmake --build . --config Release -- -quiet -jobs $NUM_OF_CORES -arch x86_64
-  #     #     retcode=$?
-  #     #     set -e
-  #     #     if [ $retcode -ne 0 ]; then
-  #     #         echo "-----------------------------------------------------------------------------------------------"
-  #     #         echo "------------------------------------ recompile without `-quiet` -------------------------------"
-  #     #         echo "-----------------------------------------------------------------------------------------------"
-  #     #         cmake --build . --config Release -- -jobs $NUM_OF_CORES -arch x86_64
-  #     #     fi
-  #     #     echo "Compile MacOSX x86_64 Release Done!"
+      #     RES_DIR=$GITHUB_WORKSPACE/templates/mac/build-mac
+      #     cd build-mac
+      #     cmake ../ -GXcode -DCMAKE_OSX_ARCHITECTURES=x86_64 -DRES_DIR=$RES_DIR -DCOCOS_X_PATH=$NATIVE_ROOT
+      #     set +e
+      #     cmake --build . --config Release -- -quiet -jobs $NUM_OF_CORES -arch x86_64
+      #     retcode=$?
+      #     set -e
+      #     if [ $retcode -ne 0 ]; then
+      #         echo "-----------------------------------------------------------------------------------------------"
+      #         echo "------------------------------------ recompile without `-quiet` -------------------------------"
+      #         echo "-----------------------------------------------------------------------------------------------"
+      #         cmake --build . --config Release -- -jobs $NUM_OF_CORES -arch x86_64
+      #     fi
+      #     echo "Compile MacOSX x86_64 Release Done!"
 
   # compile_mac_arm64:
   #   name: "MacOS arm64"
